# Generated by Django 4.2.6 on 2023-10-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('pacientes', '0002_contactoemergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PrescripcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(blank=True)),
                ('prescripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescripcion.prescripcion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='prescripcion',
            name='productos',
            field=models.ManyToManyField(through='prescripcion.PrescripcionProducto', to='productos.producto'),
        ),
    ]
